In [3]:
import numpy as np

A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A.shape  # matrice de 3 ligne et 2 colonnes

(3, 2)

### Transposée d'une matrice

In [7]:
B= A.T
B.shape 

(2, 3)

### Addition de deux matrices

In [9]:
B = np.ones((3,2))
print(B)
A + B

[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[2., 3.],
       [4., 5.],
       [6., 7.]])

### Multiplication de deux matrices

In [12]:
A.dot(B.T)   

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

### Somme de tous les élements d'une matrice

In [13]:
B.sum()

6.0